# Generated by Django 4.1.1 on 2022-09-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_profile_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.enterprise')),
                ('pants', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pants', to='employees.clothpart')),
                ('shirt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shirt', to='employees.clothpart')),
                ('shoes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shoes', to='employees.clothpart')),
            ],
        ),
    ]
