# Generated by Django 4.1.1 on 2022-09-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_enterprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='color',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='employee',
            new_name='empregado',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='size',
            new_name='tamanho',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='name',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='enterprise',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='nome',
        ),
    ]
